name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18

      - name: Install frontend Node.js dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend linters
        working-directory: frontend
        run: npm run lint

      - name: Verify code style
        working-directory: frontend
        run: npx prettier --check .
